Add note about pages-created count
x-tools/xtools pull request #64
Opened 2017-07-25 05:53 UTC by samwilson

Also fixes up some other documentation issues.

Bug: https://phabricator.wikimedia.org/T169955

2017-07-26 13:19 UTC, ricordisamoa commented on i18n/en.json
> +  "pages-created-tooltip": "Total of all pages created, inlcuding those created as a redirect when moving a page.",
typo?

2017-07-26 14:44 UTC, MusikAnimal requested changes
needs qqq mainly, but also we might look into using a tooltip rather than using the `title=` attribute

2017-07-26 14:44 UTC, MusikAnimal commented on i18n/en.json
> +  "pages-created-tooltip": "Total of all pages created, inlcuding those created as a redirect when moving a page.",
qqq? :)

2017-07-26 14:44 UTC, MusikAnimal commented on app/Resources/views/editCounter/general_stats.html.twig
> +                </td>
This works but the only way to see the translated message is to hover and _wait_ over the info icon. Most will click on the link which is only in English. If you want we could use our own tooltip system which will make the translatable message more prominent https://github.com/x-tools/xtools/blob/master/app/Resources/views/macros/forms.html.twig#L5-L11

2017-07-27 06:13 UTC, samwilson commented on i18n/en.json
> +  "pages-created-tooltip": "Total of all pages created, inlcuding those created as a redirect when moving a page.",
oops! done.

2017-07-27 06:13 UTC, samwilson commented on app/Resources/views/editCounter/general_stats.html.twig
> +                </td>
I've switched to the `tooltipcss` system, and added a couple of bits to that system; see what you think.

2017-07-27 06:14 UTC, samwilson commented
Please re-review.

2017-07-27 20:31 UTC, MusikAnimal commented
Good stuff! I add some minor CSS changes

2017-07-27 20:31 UTC, merged