ArticleInfo: add gadget to repo, with endpoint to fetch JS
x-tools/xtools pull request #90
Opened 2017-08-23 16:14 UTC by MusikAnimal

The generated file will automatically point to the API for the
current XTools installation. You can pass ?uglify=1 to uglify.

2017-08-23 16:16 UTC, MusikAnimal commented
Doing it this way because ideally we wouldn't make our script WMF-specific. For the same reason I don't think we want the uglified version in our repo either. So here there's just an endpoint at `/articleinfo-gadget.js` that will return working JS for the current XTools installation. We want to sync to the wiki, just browse to `/articleinfo-gadget.js?uglify=1` and copy/paste

2017-08-23 23:35 UTC, samwilson requested changes
Looks good! The only other thing I'd say other than these two comments is that the uglified version should contain a full URL to the place that generated the ugly, with commented instructions about updating or something. e.g. "This code was automatically generated and should not be edited here manually. For updates, please copy and paste from x."

2017-08-23 23:35 UTC, samwilson commented on src/AppBundle/Controller/ArticleInfoController.php
> +            $script = "echo \"$rendered\" | tee temp.js >/dev/null && ";
This should use a temp file in the sys temp dir, or somewhere. e.g. `$tmpFile = sys_get_temp_dir() . '/xtools_articleinfo_gadget.js';`

2017-08-23 23:35 UTC, samwilson commented on src/AppBundle/Controller/ArticleInfoController.php
> +            $process->run();
Should throw an exception if the process failed, based on `$process->getErrorOutput()`

2017-08-29 18:13 UTC, MusikAnimal commented
@samwilson ready for more review when you've time! :)

2017-08-30 16:22 UTC, Matthewrbowker approved these changes

2017-08-30 22:36 UTC, samwilson approved these changes
Looks absolutely wizard.

2017-08-30 22:58 UTC, merged